spring:
  datasource:
      username: BDC_DAK
      password: 123456
      url: jdbc:oracle:thin:@localhost:1521:orcl
      driver-class-name: oracle.jdbc.driver.OracleDriver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictionRunsMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #    filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=500
---
#spring:
#  datasource:
#    file:
#      username: bdck
#      password: YuTWsT7d
#      #
#      jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictionRunsMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      #    filters: stat,wall,log4j
#      maxPoolPreparedStatementPerConnectionSize: 20
#      useGlobalDataSourceStat: true
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=500

